//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier_Management_REST_WEB_API.Models
{
    using Courier_Management_REST_WEB_API.Links;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Serialization;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.Employee_Problems = new HashSet<Employee_Problems>();
            this.Employees = new HashSet<Employee>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        [Required,MinLength(3)]
        public string UserName { get; set; }
        [Required,EmailAddress]
        public string EmailAddress { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        [Required,MinLength(4)]
        public string Password { get; set; }
        [Required]
        public int UserType { get; set; }
        [Required]
        public int Status { get; set; }
        public string image { get; set; }
        [JsonIgnore,XmlIgnore]
        public List<Link> links = new List<Link>();
        
        public List<Link> Links
        {
            get { return links; }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore, XmlIgnore]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore, XmlIgnore]
        public virtual ICollection<Employee_Problems> Employee_Problems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore, XmlIgnore]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore, XmlIgnore]
        public virtual ICollection<Product> Products { get; set; }
    }
}
